from setuptools import setup

setup(
    name='python-kata',
    version='',
    packages=['venv.Lib.site-packages.py', 'venv.Lib.site-packages.py._io', 'venv.Lib.site-packages.py._log',
              'venv.Lib.site-packages.py._code', 'venv.Lib.site-packages.py._path',
              'venv.Lib.site-packages.py._process', 'venv.Lib.site-packages.py._vendored_packages',
              'venv.Lib.site-packages.attr', 'venv.Lib.site-packages.pluggy', 'venv.Lib.site-packages._pytest',
              'venv.Lib.site-packages._pytest.mark', 'venv.Lib.site-packages._pytest._code',
              'venv.Lib.site-packages._pytest.config', 'venv.Lib.site-packages._pytest.assertion',
              'venv.Lib.site-packages.colorama', 'venv.Lib.site-packages.atomicwrites',
              'venv.Lib.site-packages.more_itertools', 'venv.Lib.site-packages.more_itertools.tests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations', 'katas', 'katas.fizz_buzz',
              'katas.programming_101', 'katas.roman_calculator', 'katas.number_guessing_game', 'poker.betting',
              'poker.texas_holdem', 'bowling', 'home_work', 'kata_solution', 'kata_solution.bowling',
              'kata_solution.fizz_buzz', 'kata_solution.fizz_buzz._1', 'kata_solution.programming_101',
              'kata_solution.programming_101._1', 'kata_solution.programming_101._1.programming_101',
              'kata_solution.programming_101._2', 'kata_solution.programming_101._3',
              'kata_solution.programming_101._4', 'kata_solution.programming_101._5',
              'kata_solution.programming_101._6', 'kata_solution.programming_101._7', 'russian_roulette',
              'head_first_python', 'head_first_python.chapter_1', 'head_first_python.chapter_1.panic',
              'head_first_python.chapter_1.panic.pyc', 'head_first_python.chapter_3',
              'head_first_python.chapter_3.dic_practice', 'head_first_python.chapter_4', 'chess_game_practice',
              'chess_game_practice.commands', 'head_first_learn_to_code',
              'head_first_learn_to_code.learn_to_code_chapter_4'],
    url='',
    license='',
    author='jrj92',
    author_email='',
    description=''
)
